name: Create a tag with modified source after tag creation

on:
  push:
    tags:
      - '*'
jobs:
  process-release-check:
    runs-on: ubuntu-latest
    outputs:
      process: ${{ steps.check.outputs.process }}
    steps:
      - id: log
        name: log
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "x$TAG_NAME"
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo "true"; else echo "false"; fi

      - id: check
        name: check
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: echo "::set-output name=process::$(if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo "true"; else echo "false"; fi)"
  build-release:
    needs: process-release-check
    if: needs.process-release-check.outputs.process == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Update image tag
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: >
          yq -i e '.images |= [{"name": "localhost/some-image", "newName": "public.host/some-image", "newTag": "1.2.3"}]' bases/test/kustomization.yaml

      - name: Build bundle
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: >
          mkdir bundle &&
          kustomize build bases/test-ns > bundle/k8s.yaml

      - name: Push
        env:
          TAG_NAME: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email "${ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Adding extra content for $TAG_NAME"
          git tag -a "$TAG_NAME.k8s" -m "Adding extra content for $TAG_NAME"
          git push origin "refs/tags/$TAG_NAME.k8s"
