name: Create a tag with modified source after tag creation

on:
  push:
    tags:
      - '*'
jobs:
  process-release-check:
    runs-on: ubuntu-latest
    outputs:
      process: ${{ steps.check.outputs.process }}
    steps:
      - id: log
        name: log
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo "true"; else echo "false"; fi

      - id: check
        name: check
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: echo "::set-output name=process::$(if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo "true"; else echo "false"; fi)"
  build-release:
    needs: process-release-check
    if: needs.process-release-check.outputs.process == 'true'
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2.4.0

      - run: echo "action executed"
